#ifndef LOCAL_SERVER_LOCAL_SERVER_THREAD_PUBLIC_H
#define LOCAL_SERVER_LOCAL_SERVER_THREAD_PUBLIC_H

#include "../01-interface/01-ILocalServerChannel.h"

#endif // LOCAL_SERVER_LOCAL_SERVER_THREAD_PUBLIC_H